### ISSUE TITLE
Setting concurrency to 0 results in no execution

### ISSUE THREAD

**Issue by PrinceS25** [samrith-s/concurrent-tasks#22]
On the website it states, `Set 0 which translates to Infinity to make all the tasks execute in concurrence`. When I set concurrency to 0, it simply does not execute any functions. 

Here's a snapshot of my code: 
```js
const runner = new TaskRunner({
    concurrency: 0,
    autoStart: true,
    onStart: () => {
        console.log()
        console.info(moment().format(MOMENT_FORMAT) + ': Starting check...')
    },
    ...
```

I am using version 1.0.7, the one from [npmjs.com](https://www.npmjs.com/package/concurrent-tasks)

**Comment by samrith-s** [comment]
Hey @PrinceS25 

I will have a look at this. But maybe could you give v2 a try? It's in beta but is relatively stable. I'm going to deprecate v1 soon. :)

**Comment by PrinceS25** [comment]
Will do! Is usage relatively the same?

**Comment by samrith-s** [comment]
Yep it is. It's just an internal rewrite which exposes some ways to implement your own strategy. Also it's written completely in TypeScript for better completion.

**Comment by PrinceS25** [comment]
Yeah, v2 seems to work as expected in terms of concurrency but onEnd doesn't execute at all. When trying to add in the following way, it says `TypeError: Cannot add property onStart, object is not extensible`
```js
const runner = new TaskRunner();
runner.onStart = ({ duration }) => {
...
```

Perhaps I'll wait until v2 is done. Thanks!

**Comment by PrinceS25** [comment]
I don't know if it will help, but console logging `runner.isBusy()` returns true even on the last task's `done` event.
