### ISSUE TITLE
Concurrency not in the expected order (FIFO) 

### ISSUE THREAD

**Issue by joao-abreu** [samrith-s/concurrent-tasks#38]
Working on a small example got unexpected results.
Function update is async and updating data in server. By looking to network I can see:
1st post body - {name: 'test_1'}
2nd post body - {name: 'test_5'}
3rd post body - {name: 'test_4'}
4th post body - {name: 'test_3'}
5th post body - {name: 'test_2'}

`
const runner = new TaskRunner({
    concurrency: 1,
    onEnd: (data) => {
      console.log(data);
    },
  });

for (let i = 1; i <= 5; i++) {
  update({
    name: 'test_' + i
  });
}

async function update(data) {
    runner.add((done) => {
      doUpdate(data).then(() => {
        done();
      });
    });
  }
`

**Comment by samr11th** [comment]
Hello @joao-abreu sorry for the delayed reply!

That is strange, the network tab should ideally look be in the order you are expecting. Do you have a minimum reproducible example?

**Comment by samrith-s** [comment]
Hello @joao-abreu sorry for the delayed reply!

That is strange, the network tab should ideally look be in the order you are expecting. Do you have a minimum reproducible example?

**Comment by samrith-s** [comment]
Marking as stale
