### ISSUE TITLE
[Bug] import fails on dev with Vite

### ISSUE THREAD

**Issue by Max-Makhrov** [samrith-s/concurrent-tasks#53]
**Describe the bug**
The error appears after I run `npm run dev`:
```
Error: Build failed with 1 error:
node_modules/concurrent-tasks/es/index.js:11:74: ERROR: 
No matching export in "node_modules/concurrent-tasks/es/PrivateFunctions.js" for import "setAppropriateConcurrency"
```

**To Reproduce**
1. install project on Vite locally: `npm create vite@latest`
2. add import to JS file `import TaskRunner from 'concurrent-tasks';`
3. install concurrent-tasks: `npm install concurrent-tasks`
4. Run dev `npm run dev`
5. See error

**Expected behavior**
Wanted the test [shown here](https://concurrent-tasks.js.org/getting-started) to run.

**Desktop:**
 - OS: [Windows]
 - Vite: "^4.3.9"

**Screenshots**

Error:
![image](https://github.com/samrith-s/concurrent-tasks/assets/19220852/2b71cd97-523f-45f5-bd60-3ec41df56861)

package.json
![image](https://github.com/samrith-s/concurrent-tasks/assets/19220852/c5ebd967-b62a-4873-bba1-2f78b14ebd1e)

**Comment by Max-Makhrov** [comment]
I went to `index.js`

`node_modules\concurrent-tasks\es\index.js`

And deleted `setAppropriateConcurrency` from this line:

```
import { startCheckAndRun, runPending, startCheck, addCheck, removeCheck, setAppropriateConcurrency } from './PrivateFunctions';
```

**Comment by samrith-s** [comment]
Hello @Max-Makhrov !

So sorry for the delayed reply. I haven't had much time to look at this library.

If you're still using this, I'll be pushing out v3 sometime this month which should provide better type safety, more events and ideally address this issue as well.

**Comment by samrith-s** [comment]
@Max-Makhrov I've just release `v3` with a host of changes. Can you try it out and let me know if it resolves this issue? https://github.com/samrith-s/concurrent-tasks/releases/tag/v3.0.0

**Comment by samrith-s** [comment]
Closing this, since `v3` should fix it.
